Fix lastfm workflow checkout

diff --git a/.github/workflows/lastfm.yml b/.github/workflows/lastfm.yml
--- a/.github/workflows/lastfm.yml
+++ b/.github/workflows/lastfm.yml
@@ -8,6 +8,8 @@ on:
 jobs:
   fetch-and-deploy:
     runs-on: ubuntu-latest
+    env:
+      OUTPUT_FILE: "lastfm.json"
 
     steps:
       - name: Checkout code
@@ -26,8 +28,8 @@ jobs:
             exit 1
           fi
 
-          loved_data=$(jq '{lovedTracks: .lovedtracks.track[0]}' loved_data.json)
-          recent_data=$(jq '{recentTracks: .recenttracks.track}' recent_data.json)
+          loved_data=$(jq '.lovedtracks.track[0]' loved_data.json)
+          recent_data=$(jq '.recenttracks.track' recent_data.json)
 
           echo "{\"obsession\": $loved_data, \"recent\": $recent_data}" > temp_data.json
 
@@ -35,11 +37,7 @@ jobs:
 
       - name: Check for changes
         run: |
-          curl -s -o cache_data.json "https://apibayrockdev.vercel.app/lastfm.json"
-          if [ ! -s cache_data.json ]; then
-            echo "Error: Failed to fetch cache data!"
-            exit 1
-          fi
+          curl -s -o cache_data.json "https://apibayrockdev.vercel.app/$OUTPUT_FILE"
 
           if cmp --silent temp_data.json cache_data.json; then
             echo "No changes detected; skipping deployment."
@@ -52,8 +50,17 @@ jobs:
       - name: Update API data
         if: env.no_changes == null
         run: |
-          mkdir -p ./public
-          mv temp_data.json ./public/lastfm.json
+          if [ ! -f "public/endpoints.json" ]; then
+            echo "Error: Failed to locate endpoints.json!"
+            exit 1
+          fi
+
+          for file in $(jq -r '.files[]' public/endpoints.json); do
+            if [[ "$file" == "$OUTPUT_FILE" ]]; then continue; fi
+            curl -s "https://apibayrockdev.vercel.app/$file" -o "public/$file"
+          done
+
+          mv temp_data.json "./public/$OUTPUT_FILE"
 
       - name: Deploy to Vercel
         if: env.no_changes == null
